all: e1 e2 e3 e4 e5 e6 e7 e8 e9 e10 e11 e12 e13 e14 e15 e16 e17 e18 e19 e20 e21 e22

e1: e1.c
	gcc -ggdb -std=c99 -Wall -Werror -Wformat=0 -o e1 e1.c -lm
	
e2: e2.c
	gcc -ggdb -std=c99 -Wall -Werror -Wformat=0 -o e2 e2.c -lcc50 -lm
	
e3: e3.c
	gcc -ggdb -std=c99 -Wall -Werror -Wformat=0 -o e3 e3.c -lcc50 -lm
	
e4: e4.c
	gcc -ggdb -std=c99 -Wall -Werror -Wformat=0 -o e4 e4.c -lcc50 -lm
	
e5: e5.c
	gcc -ggdb -std=c99 -Wall -Werror -Wformat=0 -o e5 e5.c -lcc50 -lm
	
e6: e6.c
	gcc -ggdb -std=c99 -Wall -Werror -Wformat=0 -o e6 e6.c -lcc50 -lm
	
e7: e7.c
	gcc -ggdb -std=c99 -Wall -Werror -Wformat=0 -o e7 e7.c -lcc50 -lm
	
e8: e8.c
	gcc -ggdb -std=c99 -Wall -Werror -Wformat=0 -o e8 e8.c -lcc50 -lm
	
e9: e9.c
	gcc -ggdb -std=c99 -Wall -Werror -Wformat=0 -o e9 e9.c -lcc50 -lm
	
e10: e10.c
	gcc -ggdb -std=c99 -Wall -Werror -Wformat=0 -o e10 e10.c -lcc50 -lm

e11: e11.c
	gcc -ggdb -std=c99 -Wall -Werror -Wformat=0 -o e11 e11.c -lm
	
e12: e12.c
	gcc -ggdb -std=c99 -Wall -Werror -Wformat=0 -o e12 e12.c -lcc50 -lm
	
e13: e13.c
	gcc -ggdb -std=c99 -Wall -Werror -Wformat=0 -o e13 e13.c -lcc50 -lm
	
e14: e14.c
	gcc -ggdb -std=c99 -Wall -Werror -Wformat=0 -o e14 e14.c -lcc50 -lm
	
e15: e15.c
	gcc -ggdb -std=c99 -Wall -Werror -Wformat=0 -o e15 e15.c -lcc50 -lm
	
e16: e16.c
	gcc -ggdb -std=c99 -Wall -Werror -Wformat=0 -o e16 e16.c -lcc50 -lm
	
e17: e17.c
	gcc -ggdb -std=c99 -Wall -Werror -Wformat=0 -o e17 e17.c -lcc50 -lm
	
e18: e18.c
	gcc -ggdb -std=c99 -Wall -Werror -Wformat=0 -o e18 e18.c -lcc50 -lm
	
e19: e19.c
	gcc -ggdb -std=c99 -Wall -Werror -Wformat=0 -o e19 e19.c -lcc50 -lm
	
e20: e20.c
	gcc -ggdb -std=c99 -Wall -Werror -Wformat=0 -o e20 e20.c -lcc50 -lm
	
e21: e21.c
	gcc -ggdb -std=c99 -Wall -Werror -Wformat=0 -o e21 e21.c -lcc50 -lm
	
e22: e22.c
	gcc -ggdb -std=c99 -Wall -Werror -Wformat=0 -o e22 e22.c -lcc50 -lm
